// src/features/cad/viewport/CadViewport.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { Canvas } from '@threlte/core'
  import type { MeshSnapshot } from '../../../cad-contract/messages'
  import type { ModelParameterValues } from '../../../cad-contract/units'
  import CadViewportScene from './CadViewportScene.svelte'

  type Props = {
    mesh: MeshSnapshot | null
    modelRevision: string | null
    parameters: ModelParameterValues | null
    stale: boolean
  }

  let { mesh, modelRevision, parameters, stale }: Props = $props()
  let webglSupported = $state(true)

  function canCreateWebGLContext(): boolean {
    if (typeof document === 'undefined') return false
    const canvas = document.createElement('canvas')
    return Boolean(
      canvas.getContext('webgl') || canvas.getContext('experimental-webgl'),
    )
  }

  onMount(() => {
    webglSupported = canCreateWebGLContext()
  })
</script>

<div
  class={`viewport relative h-[min(520px,calc(100vh-15rem))] self-start overflow-hidden rounded-2xl border max-cad:h-[520px] ${stale ? 'border-stale' : 'border-border-card'} bg-viewport`}
  data-testid="cad-viewport"
  role="img"
  aria-label="3D CAD 預覽"
>
  <div class="viewport-surface">
    {#if !webglSupported}
      <div
        class="flex h-full items-center justify-center text-muted"
        role="alert"
      >
        無法建立 3D 預覽，請確認瀏覽器支援 WebGL。
      </div>
    {:else if mesh && modelRevision}
      <!-- Threlte owns the canvas lifecycle and Three.js render loop. -->
      <Canvas>
        <CadViewportScene {mesh} {modelRevision} {parameters} />
      </Canvas>
    {:else}
      <div class="flex h-full items-center justify-center text-muted">
        尚未有可預覽的模型。
      </div>
    {/if}
  </div>
  {#if stale}
    <span
      class="absolute bottom-4 left-4 rounded-full border border-stale bg-stale-background px-[0.7rem] py-[0.35rem] text-[0.85rem] text-stale-text"
    >
      預覽與目前輸入不同步
    </span>
  {/if}
</div>

<style>
  .viewport {
    --viewport-radius: 2rem;
  }

  .viewport-surface {
    height: 100%;
    overflow: hidden;
    border-radius: calc(var(--viewport-radius) - 1px);
    isolation: isolate;
  }

  .viewport :global(canvas) {
    display: block;
    width: 100% !important;
    height: 100% !important;
    border-radius: calc(var(--viewport-radius) - 1px);
  }
</style>

// src/features/cad/viewport/CadViewport.tsx
import { Bounds, OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { useEffect, useMemo } from "react";
import * as THREE from "three";
import type { MeshSnapshot } from "../../../cad-contract/messages";
import styles from "./CadViewport.module.scss";

function ModelMesh({ mesh }: { mesh: MeshSnapshot }) {
  const geometry = useMemo(() => {
    const nextGeometry = new THREE.BufferGeometry();
    nextGeometry.setAttribute("position", new THREE.BufferAttribute(new Float32Array(mesh.positions), 3));
    nextGeometry.setAttribute("normal", new THREE.BufferAttribute(new Float32Array(mesh.normals), 3));
    nextGeometry.setIndex(new THREE.BufferAttribute(new Uint32Array(mesh.indices), 1));
    nextGeometry.computeBoundingSphere();
    return nextGeometry;
  }, [mesh]);
  const material = useMemo(
    () => new THREE.MeshStandardMaterial({ color: "#4e7cff", metalness: 0.18, roughness: 0.42 }),
    []
  );

  useEffect(() => () => geometry.dispose(), [geometry]);
  useEffect(() => () => material.dispose(), [material]);

  return <mesh dispose={null} geometry={geometry} material={material} />;
}

type CadViewportProps = {
  mesh: MeshSnapshot | null;
  stale: boolean;
};

function ViewportContent({ mesh }: { mesh: MeshSnapshot | null }) {
  if (!mesh) {
    return <div className="flex h-[520px] items-center justify-center text-muted">尚未有可預覽的模型。</div>;
  }

  return (
    <Canvas
      aria-label="3D CAD 預覽"
      fallback={
        <div className="flex h-[520px] items-center justify-center text-muted" role="alert">
          無法建立 3D 預覽，請確認瀏覽器支援 WebGL。
        </div>
      }
      camera={{ position: [100, 100, 100], fov: 45 }}
    >
      <color attach="background" args={["#eef2f8"]} />
      <ambientLight intensity={1.6} />
      <directionalLight position={[100, 120, 80]} intensity={2.2} />
      <gridHelper args={[1000, 20, "#b9c4d7", "#d8deea"]} />
      <Bounds fit clip observe margin={1.25}>
        <ModelMesh mesh={mesh} />
      </Bounds>
      <OrbitControls makeDefault />
    </Canvas>
  );
}

export function CadViewport({ mesh, stale }: CadViewportProps) {
  const viewportBorderClassName = stale ? "border-stale" : "border-border-card";

  return (
    <div
      className={`relative min-h-[520px] overflow-hidden rounded-2xl border ${viewportBorderClassName} bg-viewport ${styles.viewport}`}
      data-testid="cad-viewport"
      role="img"
      aria-label="3D CAD 預覽"
    >
      <ViewportContent mesh={mesh} />
      {stale && (
        <span className="absolute bottom-4 left-4 rounded-full border border-stale bg-stale-background px-[0.7rem] py-[0.35rem] text-[0.85rem] text-stale-text">
          預覽與目前輸入不同步
        </span>
      )}
    </div>
  );
}
