// src/components/cad/component-panels/index.tsx
import type { ComponentType } from 'react'
import type { ModelId } from '../../../cad-contract/units'
import { BoxComponentPanel } from './box/BoxComponentPanel'
import { ModularGridBaseComponentPanel } from './modular-grid-base/ModularGridBaseComponentPanel'
import type { ComponentPanelProps } from './types'

const componentPanels: Record<ModelId, ComponentType<ComponentPanelProps>> = {
  box: BoxComponentPanel,
  'modular-grid-base': ModularGridBaseComponentPanel,
}

export function ComponentParameterPanel({
  modelId,
  ...props
}: ComponentPanelProps & { modelId: ModelId }) {
  const Panel = componentPanels[modelId]
  return <Panel {...props} />
}

// src/components/cad/component-panels/index.svelte
<script lang="ts">
  import type { ModelId } from '../../../cad-contract/units'
  import BoxComponentPanel from './box/BoxComponentPanel.svelte'
  import ModularGridBaseComponentPanel from './modular-grid-base/ModularGridBaseComponentPanel.svelte'
  import type { ComponentPanelProps } from './types'

  type Props = ComponentPanelProps & {
    modelId: ModelId
  }

  let { modelId, rawParameters, fieldErrors, onInputChange }: Props = $props()
</script>

{#if modelId === 'box'}
  <BoxComponentPanel {rawParameters} {fieldErrors} {onInputChange} />
{:else}
  <ModularGridBaseComponentPanel
    {rawParameters}
    {fieldErrors}
    {onInputChange}
  />
{/if}
