// src/components/cad/CadWorkspace.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import type { ModelId, ModelParameterKey } from '../../cad-contract/units'
  import type { ExportFormat } from '../../features/cad/download'
  import CadViewport from '../../features/cad/viewport/CadViewport.svelte'
  import CadWorkspacePanel from './CadWorkspacePanel.svelte'
  import {
    createCadWorkspaceController,
    type CadWorkspaceController,
    type CadWorkspaceControllerSnapshot,
  } from './workspace/createCadWorkspaceController'

  type Props = {
    modelId: ModelId
  }

  let { modelId }: Props = $props()
  let snapshot = $state<CadWorkspaceControllerSnapshot | null>(null)
  let controller: CadWorkspaceController | null = null

  onMount(() => {
    controller = createCadWorkspaceController(modelId, (nextSnapshot) => {
      snapshot = nextSnapshot
    })

    return () => {
      controller?.dispose()
      controller = null
    }
  })

  function handleInputChange(key: ModelParameterKey, value: string): void {
    controller?.onInputChange(key, value)
  }

  function handleExport(format: ExportFormat): void {
    controller?.onExport(format)
  }

  function handleRetry(): void {
    controller?.onRetry()
  }
</script>

{#if snapshot}
  <div
    class="mt-6 grid items-start grid-cols-[minmax(220px,280px)_minmax(0,1fr)] gap-4 max-cad:grid-cols-1"
    data-testid="cad-workspace"
  >
    <CadWorkspacePanel
      state={snapshot.state}
      modelId={snapshot.modelId}
      rawParameters={snapshot.rawParameters}
      fieldErrors={snapshot.fieldErrors}
      progress={snapshot.progress}
      status={snapshot.status}
      canExport={snapshot.canExport}
      onInputChange={handleInputChange}
      onExport={handleExport}
      onRetry={handleRetry}
    />
    <CadViewport
      mesh={snapshot.state.committed?.mesh ?? null}
      parameters={snapshot.state.committed?.parameters ?? null}
      stale={snapshot.state.stale}
    />
  </div>
{/if}

// src/components/cad/CadWorkspace.tsx
import { CadViewport } from '../../features/cad/viewport/CadViewport'
import type { ModelId } from '../../cad-contract/units'
import { CadWorkspacePanel } from './CadWorkspacePanel'
import { useCadWorkspaceController } from './workspace/useCadWorkspaceController'

type CadWorkspaceProps = {
  modelId: ModelId
}

export default function CadWorkspace({ modelId }: CadWorkspaceProps) {
  const controller = useCadWorkspaceController(modelId)

  return (
    <div
      className="mt-6 grid items-start grid-cols-[minmax(220px,280px)_minmax(0,1fr)] gap-4 max-cad:grid-cols-1"
      data-testid="cad-workspace"
    >
      <CadWorkspacePanel
        state={controller.state}
        modelId={controller.modelId}
        rawParameters={controller.rawParameters}
        fieldErrors={controller.fieldErrors}
        progress={controller.progress}
        status={controller.status}
        canExport={controller.canExport}
        onInputChange={controller.onInputChange}
        onExport={controller.onExport}
        onRetry={controller.onRetry}
      />
      <CadViewport
        mesh={controller.state.committed?.mesh ?? null}
        parameters={controller.state.committed?.parameters ?? null}
        stale={controller.state.stale}
      />
    </div>
  )
}
