// src/components/cad/CadWorkspacePanel.tsx
import { getModelDefinition } from '../../features/cad/model-catalog'
import type { CadState } from '../../features/cad/state'
import type { ModelId, ModelParameterKey } from '../../cad-contract/units'
import type { CadProgress } from '../../features/cad/progress'
import type { ExportFormat } from '../../features/cad/download'
import type { RawParameters } from './workspace/types'
import { ComponentParameterPanel } from './component-panels'
import { CadProgressIndicator } from './CadProgressIndicator'

const ACTION_BUTTON_CLASS =
  'cursor-pointer rounded-lg border-0 bg-primary px-[0.8rem] py-[0.6rem] text-base text-white disabled:cursor-not-allowed disabled:bg-disabled'

type CadWorkspacePanelProps = {
  state: CadState
  modelId: ModelId
  rawParameters: RawParameters
  fieldErrors: Partial<Record<ModelParameterKey, string>>
  progress: CadProgress | null
  status: string
  canExport: boolean
  onInputChange: (key: ModelParameterKey, value: string) => void
  onExport: (format: ExportFormat) => void
  onRetry: () => void
}

export function CadWorkspacePanel({
  state,
  modelId,
  rawParameters,
  fieldErrors,
  progress,
  status,
  canExport,
  onInputChange,
  onExport,
  onRetry,
}: CadWorkspacePanelProps) {
  const definition = getModelDefinition(modelId)
  if (!definition) throw new Error(`UNKNOWN_MODEL_ID:${modelId}`)

  return (
    <div className="self-start grid gap-4 rounded-2xl border border-border-card bg-panel p-4">
      <div>
        <h2 className="mb-2 text-2xl font-semibold leading-tight">
          {definition.displayName}參數
        </h2>
        <p className="text-muted">
          目前編輯此 component；如要切換模型，請
          <a className="text-ink underline underline-offset-4" href="/">
            返回首頁選擇其他模型
          </a>
          。
        </p>
      </div>
      <ComponentParameterPanel
        modelId={modelId}
        rawParameters={rawParameters}
        fieldErrors={fieldErrors}
        onInputChange={onInputChange}
      />
      {progress && <CadProgressIndicator progress={progress} />}
      <div className="flex flex-wrap gap-[0.6rem]">
        <button
          className={ACTION_BUTTON_CLASS}
          type="button"
          disabled={!canExport}
          onClick={() => onExport('step')}
        >
          下載 STEP
        </button>
        <button
          className={ACTION_BUTTON_CLASS}
          type="button"
          disabled={!canExport}
          onClick={() => onExport('stl')}
        >
          下載 STL
        </button>
        {(state.status === 'recoverable-error' ||
          state.status === 'fatal-worker-error') && (
          <button
            className={ACTION_BUTTON_CLASS}
            type="button"
            onClick={onRetry}
          >
            重試
          </button>
        )}
      </div>
      <p className="text-sm text-muted">
        STL 下載後，可在 Bambu Studio 透過本機檔案流程匯入。
      </p>
      <div
        aria-live="polite"
        className="rounded-2xl border border-border-card bg-panel p-4 text-[0.92rem] text-status"
        role="status"
      >
        <strong className="text-ink">狀態：</strong> {status}
        {state.stale && (
          <div className="text-muted">目前預覽是上一個成功 revision。</div>
        )}
        {state.error && (
          <div className="text-sm text-error" role="alert">
            錯誤代碼：{state.error.code}
          </div>
        )}
      </div>
    </div>
  )
}

// src/components/cad/CadWorkspacePanel.svelte
<script lang="ts">
  import type { CadState } from '../../features/cad/state'
  import type {
    ModelId,
    ModelParameterKey,
    ModelParameterValues,
    OpenGridParameters,
  } from '../../cad-contract/units'
  import type { ExportFormat } from '../../features/cad/download'
  import { getModelDefinition } from '../../features/cad/model-catalog'
  import type { RawParameters } from './workspace/types'
  import ComponentParameterPanel from './component-panels/index.svelte'
  import RestoreDefaultsButton from './component-panels/RestoreDefaultsButton.svelte'

  const ACTION_BUTTON_CLASS =
    'cursor-pointer rounded-lg border-0 bg-primary px-[0.8rem] py-[0.6rem] text-base text-white disabled:cursor-not-allowed disabled:bg-disabled'

  type Props = {
    state: CadState
    modelId: ModelId
    parameters: ModelParameterValues
    rawParameters: RawParameters
    fieldErrors: Partial<Record<ModelParameterKey | 'parameters', string>>
    canExport: boolean
    onInputChange: (key: ModelParameterKey, value: string) => void
    onOpenGridParametersChange: (parameters: OpenGridParameters) => void
    onOpenGridDimensionCalculationInvalid: () => void
    onExport: (format: ExportFormat) => void
    onRetry: () => void
    resetVersion: number
    onRestoreDefaults: () => void
  }

  let {
    state,
    modelId,
    parameters,
    rawParameters,
    fieldErrors,
    canExport,
    onInputChange,
    onOpenGridParametersChange,
    onOpenGridDimensionCalculationInvalid,
    onExport,
    onRetry,
    resetVersion,
    onRestoreDefaults,
  }: Props = $props()

  function hasParameterControlsFor(modelId: ModelId): boolean {
    if (modelId === 'opengrid' || modelId === 'opengrid-pillar') return true
    return (getModelDefinition(modelId)?.parameterSchema.length ?? 0) > 0
  }
</script>

<div
  class="sticky top-4 self-start grid min-h-0 max-h-[calc(100dvh-16rem)] gap-4 overflow-y-auto rounded-2xl border border-border-card bg-panel p-4 max-cad:static max-cad:max-h-none max-cad:overflow-visible"
  data-testid="cad-workspace-panel"
>
  {#if hasParameterControlsFor(modelId)}
    <RestoreDefaultsButton onRestore={onRestoreDefaults} />
    {#key resetVersion}
      <ComponentParameterPanel
        {modelId}
        {parameters}
        {rawParameters}
        {fieldErrors}
        {onInputChange}
        {onOpenGridParametersChange}
        {onOpenGridDimensionCalculationInvalid}
      />
    {/key}
  {/if}
  <div class="flex flex-wrap gap-[0.6rem]">
    <button
      class={ACTION_BUTTON_CLASS}
      type="button"
      disabled={!canExport}
      onclick={() => onExport('step')}
    >
      下載 STEP
    </button>
    <button
      class={ACTION_BUTTON_CLASS}
      type="button"
      disabled={!canExport}
      onclick={() => onExport('stl')}
    >
      下載 STL
    </button>
    {#if state.status === 'recoverable-error' || state.status === 'fatal-worker-error'}
      <button class={ACTION_BUTTON_CLASS} type="button" onclick={onRetry}>
        重試
      </button>
    {/if}
  </div>
  <p class="text-sm text-muted">
    STL 下載後，可在 Bambu Studio 透過本機檔案流程匯入。
  </p>
</div>
